# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20171007_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='password',
            new_name='username',
        ),
    ]
