# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='time',
            new_name='post_time',
        ),
    ]
