# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20171008_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
