# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '__first__'),
        ('course', '0013_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instructor.Course'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instructor.Course'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instructor.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_list',
            field=models.ManyToManyField(to='instructor.Course'),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
