# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 11:04
from __future__ import unicode_literals

from django.db import migrations
# import likert_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='submission',
        #     name='feedback',
        #     field=likert_field.models.LikertField(blank=True, null=True),
        # ),
    ]
